server:
  port: 8080
database:
  driver_name: mysql
  host_name: root:Moto@688729@tcp(127.0.0.1:3306)
  db_name: testDb
pagination:
  page_size: 10
ticker:
  time: 1
api:
  keys: [AIzaSyAwcp16qimeqGJ2LdfmjpevUc3voIGLIuw,AIzaSyA1q2z3Ce3O6Df0xAng-DPs7lc9ZJrTPtk]
  query: tutorial