version: '4.16.2'

services:

  db:
    image: mysql:8.0.32 # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 5s
      timeout: 10s
      retries: 5
  go:
    build: # Use the Dockerfile from the current directory to build container.
      context: .
      dockerfile: go.dockerfile
    container_name: go
    ports:
      - "8080:8081"
    restart: on-failure:2
    depends_on:
      db:
        condition: service_healthy

volumes: # add volume to persist data.
  my-db:
networks:
  default: